version: "3.8"

services:
  jupyter:
    # image: jupyter/scipy-notebook:python-3.10.11
    image: rjurney/graphml-class
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter
    ports:
      - 8888:8888
    volumes:
      - .:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - DGLBACKEND=pytorch
    env_file:
      - envs/graphistry.env
      - envs/search.env
      - envs/openai.env
      - envs/wandb.env
      - .env
    restart: always

  neo4j:
    image: neo4j:5.25.1
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data/neo4j:/data
      - ./logs/neo4j:/logs
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    env_file:
      - envs/neo4j.env
      - .env
    restart: always

